[appearance]
	# 項目名：検索バーを中央に移動
	# 説明：JEIの検索バーを画面の中央下部に移動します。
	# 有効値：[true, false]
	# デフォルト値：false
	centerSearch = false

	# 項目名：レシピGUIの最大高さ
	# 説明：レシピGUIの最大高さ（ピクセル）。
	# 有効値：Any integer greater than or equal to 175
	# デフォルト値：350
	recipeGuiHeight = 350

	# 項目名：Toast Reflow
	# 説明：Reserves space for toast notifications so they do not overlap the JEI interface.
	# 有効値：[true, false]
	# デフォルト値：true
	toastReflowEnabled = true


[cheating]
	# 項目名：付与モード
	# 説明：JEIがアイテムをインベントリに直接与えるか、マウスで拾うかを選択します
	# 有効値：[INVENTORY, MOUSE_PICKUP]
	# デフォルト値：MOUSE_PICKUP
	giveMode = MOUSE_PICKUP

	# 項目名：ホットキーを使用してホットバーにチートアイテムを追加
	# 説明：Shift + 数値キーを使用して、ホットバーにチートアイテムを与えられるようになります。
	# 有効値：[true, false]
	# デフォルト値：false
	cheatToHotbarUsingHotkeysEnabled = false

	# 項目名：隠されたアイテムを表示
	# 説明：クリエイティブメニューに無いアイテムを表示します。
	# 有効値：[true, false]
	# デフォルト値：false
	showHiddenIngredients = false

	# 項目名：タグレシピの表示
	# 説明：アイテムタグやブロックタグなどのタグレシピを表示します。
	# 有効値：[true, false]
	# デフォルト値：false
	showTagRecipesEnabled = false


[bookmarks]
	# 項目名：ブックマークを先頭に追加
	# 説明：trueにすると、新しいブックマークをリストの先頭に追加します。falseにすると、末尾に追加します。
	# 有効値：[true, false]
	# デフォルト値：false
	addBookmarksToFrontEnabled = false

	# 項目名：Bookmark Output as Recipe
	# 説明：When true, pressing the bookmark key on a recipe's output will bookmark the recipe instead of the ingredient.
	# 有効値：[true, false]
	# デフォルト値：true
	bookmarkOutputAsRecipe = true

	# 項目名：ドラッグでブックマークを並び替える
	# 説明：ブックマークをドラッグして、リスト内で並び替えられるようになります。
	# 有効値：[true, false]
	# デフォルト値：true
	dragToRearrangeBookmarksEnabled = true


[tooltips]
	# 項目名：ブックマークのツールチップ機能
	# 説明：ブックマークのツールチップの追加機能。
	# 有効値：A comma-separated list containing values of:
	# [PREVIEW, INGREDIENTS]
	# デフォルト値：PREVIEW
	bookmarkTooltipFeatures = PREVIEW

	# 項目名：Shiftでブックマークのツールチップを表示
	# 説明：Shiftを押すとブックマークのツールチップ機能を表示します。
	# 有効値：[true, false]
	# デフォルト値：true
	holdShiftToShowBookmarkTooltipFeatures = true

	# 項目名：クリエイティブタブ名の表示
	# 説明：アイテムのツールチップにクリエイティブタブ名を表示します。
	# 有効値：[true, false]
	# デフォルト値：false
	showCreativeTabNamesEnabled = false

	# 項目名：タグの表示
	# 説明：レシピの材料を確認するときに、ツールチップにタグの内容を表示します。
	# 有効値：[true, false]
	# デフォルト値：true
	tagContentTooltipEnabled = true

	# 項目名：単一アイテム用タグの内容を非表示
	# 説明：タグにアイテムが1種類しかないとき、ツールチップにタグの内容を表示しないようにします。
	# 有効値：[true, false]
	# デフォルト値：true
	hideSingleTagContentTooltipEnabled = true

	# 項目名：レシピの材料リスト
	# 説明：レシピの完成品にカーソルを合わせたとき、ツールチップに材料リストを表示します。
	# 有効値：[true, false]
	# デフォルト値：false
	enableRecipesGuiIngredientsSummary = false


[performance]
	# 項目名：省メモリ検索
	# 説明：検索を省メモリモードに設定します（検索は遅くなりますが、RAMの使用量が低下します）。
	# 有効値：[true, false]
	# デフォルト値：false
	lowMemorySlowSearchEnabled = false


[lookups]
	# 項目名：流体の確認
	# 説明：流体を含むアイテムのレシピを検索するとき、その流体のレシピも合わせて検索します。
	# 有効値：[true, false]
	# デフォルト値：false
	lookupFluidContentsEnabled = false

	# 項目名：アイテム／ブロックタグの確認
	# 説明：アイテムタグを検索するとき、そのアイテムに含まれるデフォルトのブロックタグも含めて表示します。
	# 有効値：[true, false]
	# デフォルト値：true
	lookupBlockTagsEnabled = true


[lookupHistory]
	# 項目名：有効化
	# 説明：検索履歴オーバーレイの表示／非表示を切り替えます
	# 有効値：[true, false]
	# デフォルト値：false
	enabled = false

	# 項目名：最大行数
	# 説明：検索履歴オーバーレイに表示される行の最大数。
	# 有効値：An integer in the range [1, 7] (inclusive)
	# デフォルト値：2
	maxRows = 2

	# 項目名：最大アイテム数
	# 説明：保存する検索履歴の最大数。
	# 有効値：An integer in the range [10, 1000] (inclusive)
	# デフォルト値：100
	maxIngredients = 100

	# 項目名：表示位置
	# 説明：検索履歴オーバーレイを表示する画面の位置。
	# 有効値：[LEFT, RIGHT]
	# デフォルト値：LEFT
	displaySide = LEFT


[advanced]
	# 項目名：レンダリングエラーのキャッチ
	# 説明：クラッシュさせる代わりに、Modのアイテムのレンダリングエラーをキャッチし、回復を試みるようになります。
	# 有効値：[true, false]
	# デフォルト値：true
	catchRenderErrorsEnabled = true


[input]
	# 項目名：ドラッグの遅延
	# 説明：マウスを長押しするとマウスのドラッグとみなされるまでのミリ秒数。
	# 有効値：An integer in the range [0, 1000] (inclusive)
	# デフォルト値：150
	dragDelayInMilliseconds = 150

	# 項目名：滑らかなスクロール速度
	# 説明：滑らかなスクロールのスクロールボックスでマウスホイールを使用する場合のスクロール速度。ピクセル単位で測定されます。
	# 有効値：An integer in the range [1, 50] (inclusive)
	# デフォルト値：9
	smoothScrollRate = 9


[sorting]
	# 項目名：アイテムのソート階層
	# 説明：アイテムリストのソート順序。
	# 有効値：A comma-separated list containing values of:
	# [MOD_NAME, INGREDIENT_TYPE, ALPHABETICAL, CREATIVE_MENU, TAG, ARMOR, MAX_DURABILITY]
	# デフォルト値：MOD_NAME, INGREDIENT_TYPE, CREATIVE_MENU
	ingredientSortStages = MOD_NAME, INGREDIENT_TYPE, CREATIVE_MENU

	# 項目名：レシピのソート階層
	# 説明：表示されるレシピのソート順序。
	# 有効値：A comma-separated list containing values of:
	# [BOOKMARKED, CRAFTABLE]
	# デフォルト値：BOOKMARKED, CRAFTABLE
	recipeSorterStages = BOOKMARKED, CRAFTABLE


[search]
	# 項目名：検索モード（@Mod名）
	# 説明：Mod名での検索モード（接頭辞：@）。
	# 有効値：[ENABLED, REQUIRE_PREFIX, DISABLED]
	# デフォルト値：REQUIRE_PREFIX
	modNameSearchMode = REQUIRE_PREFIX

	# 項目名：検索モード（#タグ）
	# 説明：タグでの検索モード （接頭辞：#）。
	# 有効値：[ENABLED, REQUIRE_PREFIX, DISABLED]
	# デフォルト値：REQUIRE_PREFIX
	tagSearchMode = REQUIRE_PREFIX

	# 項目名：検索モード（$ツールチップ）
	# 説明：ツールチップでの検索モード（接頭辞：$）
	# 有効値：[ENABLED, REQUIRE_PREFIX, DISABLED]
	# デフォルト値：ENABLED
	tooltipSearchMode = ENABLED

	# 項目名：検索モード（^色）
	# 説明：色での検索モード（接頭辞：^）。
	# 有効値：[ENABLED, REQUIRE_PREFIX, DISABLED]
	# デフォルト値：DISABLED
	colorSearchMode = DISABLED

	# 項目名：検索モード（&識別子）
	# 説明：識別子での検索モード（接頭辞：&）。
	# 有効値：[ENABLED, REQUIRE_PREFIX, DISABLED]
	# デフォルト値：DISABLED
	resourceLocationSearchMode = DISABLED

	# 項目名：検索モード（%クリエイティブタブ）
	# 説明：クリエイティブタブ名での検索モード（接頭辞：%）。
	# 有効値：[ENABLED, REQUIRE_PREFIX, DISABLED]
	# デフォルト値：DISABLED
	creativeTabSearchMode = DISABLED

	# 項目名：高度な情報での検索
	# 説明：高度な情報での検索（F3 + Hで表示）。
	# 有効値：[true, false]
	# デフォルト値：false
	searchAdvancedTooltips = false

	# 項目名：Mod IDでの検索
	# 説明：Mod名に加え、Mod IDでの検索を行います。
	# 有効値：[true, false]
	# デフォルト値：true
	searchModIds = true

	# 項目名：Modエイリアスでの検索
	# 説明：Mod名に加え、プラグインにより追加されたModエイリアス（代替名）での検索を行います。
	# 有効値：[true, false]
	# デフォルト値：true
	searchModAliases = true

	# 項目名：省略したMod名での検索
	# 説明：Mod名の頭文字での検索を行います。
	# 有効値：[true, false]
	# デフォルト値：false
	searchShortModNames = false

	# 項目名：アイテムエイリアスでの検索
	# 説明：アイテム名に加え、プラグインにより追加されたアイテムエイリアス（代替名）での検索を行います。
	# 有効値：[true, false]
	# デフォルト値：true
	searchIngredientAliases = true


[ingredientList]
	# 項目名：最大行数
	# 説明：表示される行の最大数。
	# 有効値：An integer in the range [1, 100] (inclusive)
	# デフォルト値：16
	maxRows = 16

	# 項目名：最大列数
	# 説明：表示される列の最大数。
	# 有効値：An integer in the range [2, 100] (inclusive)
	# デフォルト値：9
	maxColumns = 9

	# 項目名：水平方向の配置
	# 説明：利用可能なエリア内でのアイテムリストの水平方向の配置。
	# 有効値：[LEFT, CENTER, RIGHT]
	# デフォルト値：RIGHT
	horizontalAlignment = RIGHT

	# 項目名：垂直方向の配置
	# 説明：利用可能なエリア内でのアイテムリストの垂直方向の配置。
	# 有効値：[TOP, CENTER, BOTTOM]
	# デフォルト値：TOP
	verticalAlignment = TOP

	# 項目名：ナビゲーションの表示
	# 説明：上部のページボタンの表示設定。ページが複数ある場合のみ表示するにはAUTO_HIDEを使用してください。
	# 有効値：[ENABLED, AUTO_HIDE, DISABLED]
	# デフォルト値：ENABLED
	navigationVisibility = ENABLED

	# 項目名：GUIの背景を描画
	# 説明：trueにすると、アイテムリストの背後に背景テクスチャを描画します。
	# 有効値：[true, false]
	# デフォルト値：false
	drawBackground = false

	# 項目名：Navigation Mode
	# 説明：Choose PAGED for page buttons, SCROLLING for a row-stepped scroll bar, or SMOOTH_SCROLLING for a smooth scroll bar.
	# 有効値：[PAGED, SCROLLING, SMOOTH_SCROLLING]
	# デフォルト値：PAGED
	navigationMode = PAGED


[bookmarkList]
	# 項目名：最大行数
	# 説明：表示される行の最大数。
	# 有効値：An integer in the range [1, 100] (inclusive)
	# デフォルト値：16
	maxRows = 16

	# 項目名：最大列数
	# 説明：表示される列の最大数。
	# 有効値：An integer in the range [2, 100] (inclusive)
	# デフォルト値：9
	maxColumns = 9

	# 項目名：水平方向の配置
	# 説明：利用可能なエリア内でのブックマークリストの水平方向の配置。
	# 有効値：[LEFT, CENTER, RIGHT]
	# デフォルト値：LEFT
	horizontalAlignment = LEFT

	# 項目名：垂直方向の配置
	# 説明：利用可能なエリア内でのブックマークリストの垂直方向の配置。
	# 有効値：[TOP, CENTER, BOTTOM]
	# デフォルト値：TOP
	verticalAlignment = TOP

	# 項目名：ナビゲーションの表示
	# 説明：上部のページボタンの表示設定。ページが複数ある場合のみ表示するにはAUTO_HIDEを使用してください。
	# 有効値：[ENABLED, AUTO_HIDE, DISABLED]
	# デフォルト値：ENABLED
	navigationVisibility = ENABLED

	# 項目名：GUIの背景を描画
	# 説明：trueにすると、ブックマークリストの背後に背景テクスチャを描画します。
	# 有効値：[true, false]
	# デフォルト値：false
	drawBackground = false

	# 項目名：Navigation Mode
	# 説明：Choose PAGED for page buttons, SCROLLING for a row-stepped scroll bar, or SMOOTH_SCROLLING for a smooth scroll bar.
	# 有効値：[PAGED, SCROLLING, SMOOTH_SCROLLING]
	# デフォルト値：PAGED
	navigationMode = PAGED


