name = "Reimagined"
version = "1.21.50"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8ba8af3e39d4715713d4aa7290929c84b5fd03427ca86cab487ed1d76d48ac8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
