name = "Reimagined"
version = "1.21.50"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5efb2e1df13c183455d073c2894d99b9d1923f292770eba21097fca7c54a3da1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
