#Decreases the Mining Speed of Budding Amethyst
slowedBuddingAmethystMiningSpeed = true
#Adds Palladium Nuggets drops to Pillager Drops
pillagerDropPalladiumNugget = true
#Adds Spectre Flares to Ancient City Loot
spectreFlareAncientCityLoot = true
