#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Sep 05 13:32:52 JST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=4
shaderPack=ComplementaryReimagined_r5.8.1 + EuphoriaPatches_1.9.3
