version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = false
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "FAST"
leavesCullingAmount = 2
includeMangroveRoots = true
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
farmersdelight = true
fastitemframes = true
everycomp = true
tide = true
onion_onion = true
terrain_slabs = true
upgrade_aquatic = true
nomansland = true
betternether = true
multiplayerspawners = true
betterend = true
ribbits = true
quark = true
brewinandchewin = true
galosphere = true
cataclysm = true
clayworks = true
another_furniture = true
caverns_and_chasms = true
runes = true
natures_spirit = true
copycats = true
stonezone = true
create_enchantment_industry = true
fastpaintings = true
aether = true
amendments = true
buzzier_bees = true
mynethersdelight = true
ftbquests = true
hearthandharvest = true
snowrealmagic = true
moonlight = true
etcetera = true
sophisticatedbackpacks = true
spell_engine = true
naturalist = true
endersdelight = true
supplementaries = true
cnb = true
deeperdarker = true
create = true
paladins = true
infernalexp = true
sawmill = true
creaturefeature = true
netherman = true
deep_aether = true
createmetalwork = true
rogues = true
minecraft = true
lootr = true
rusticdelight = true
create_dragons_plus = true
mowziesmobs = true
creeperoverhaul = true
waystones = true
jewelry = true
just_dandy = true
endermanoverhaul = true
cookscollection = true
bosses_of_mass_destruction = true
decorative_blocks = true
archers = true
crittersandcompanions = true
tolerable_creepers = true
clutterbestiary = true
toms_storage = true
create_integrated_farming = true
