[stonetype]
	#Exclude StoneType from all of Modules
	#    EXAMPLE: blacklist = [
	#        "forestry:.*fireproof.*",		COMMENT: .* is an RegEx, it exclude all of StoneType containing "fireproof" from Forestry
	#        "biomesoplenty:.*",				COMMENT: .* is an RegEx, it exclude all of StoneType from Wood Mod for any Module
	#        "biomesoplenty:redwood"		COMMENT: exclude redwood from Stone Mod for any module
	#    ]
	#
	blacklist = []

[mudtype]
	#Exclude MudType from all of Modules
	#	The example is same as StoneType's
	blacklist = []

[entryset]
	#Exclude EntrySet from the module for All of StoneType or MudType
	#    This is only applied to Stone-Zone.
	#    EXAMPLE: blacklist = [
	#        "chipped:checkered_trapdoor",	COMMENT: chipped:checkered_oak_trapdoor without "oak"
	#        "variantvanillablocks:chest",	COMMENT: variantvanillablocks:oak_chest without "oak"
	#        "chipped:.*"					COMMENT: .* is an regex which will exclude all of EntrySets from one Module
	#    ]
	#
	blacklist = []
