#Prevent a slower block breaking speed caused by the player not standing on the ground while riding any vehicle.
#Default Value: true
#Requires Restart: Game
remove_passenger_mining_speed_malus = true
#Makes speed and slowness mob effects provide flying speed in addition to movement speed.
#This allows mobs such as the happy ghast and bees to benefit from these effects.
#Default Value: true
#Requires Restart: Game
speed_mob_effects_grant_flying_speed = true

[horse]
	#Set the step height for all horses above one block to be able to run up from path blocks, farmland, etc.
	#Default Value: true
	#Requires Restart: Game
	increase_horse_step_height = true
